version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: projectkaf_staging
      POSTGRES_USER: projectkaf
      POSTGRES_PASSWORD: staging_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U projectkaf"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      NODE_ENV: staging
      DATABASE_URL: postgresql://projectkaf:staging_password@postgres:5432/projectkaf_staging
      REDIS_URL: redis://redis:6379
      JWT_SECRET: staging-jwt-secret-change-in-production
      PORT: 8000
      CORS_ORIGINS: http://localhost:3000,http://localhost:3001
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
  redis_data: